name: release
on:
 workflow_call:
  outputs:
     BRANCHNAME:
       description: "release Branch"
       value: ${{ jobs.create-release.outputs.BRANCH }}
 
jobs:
 create-release:
   name: create-release
   runs-on: [ubuntu-latest]
   outputs:
     BRANCH: ${{ steps.branch.outputs.BRANCHNAME }}
  
   steps:
   - name: Check out code
     uses: actions/checkout@v4

   - name: Create release branch
      run: |
        BRANCH_NAME="release-$(date +%y-%m-%d)"
        if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
          echo "Branch $BRANCH_NAME already exists on remote. Pulling latest changes..."
          git fetch origin $BRANCH_NAME
          git checkout $BRANCH_NAME
          git pull origin $BRANCH_NAME
        else
          echo "Creating a new branch $BRANCH_NAME"
          git checkout -b $BRANCH_NAME
        fi
    - name: Push new branch
      run: git push origin release-`date +%y-%m-%d`
   - name: Getting branch name 
     id: branch
     run: echo "BRANCHNAME=release-`date +%y-%m-%d`" >> $GITHUB_OUTPUT
