name: Create Release Workflow

on:
  workflow_dispatch:
    inputs:
      Create_Branch:
        description: 'Create Release branch?'
        required: false
        type: boolean
        default: false
      BUILD_BUSINESS:
        description: 'Build Business one of In Mea Ph Sea Hsi'
        required: false
        type: 'string'
        default: 'In Mea Ph Sea Hsi'
        # If modifying `BUILD_BUSINESS`, update this value and also update the value in `build-dogfood` job (env.BUILD_BUSINESS).
      HOTFIX:
        description: 'Hotfix Build Generation?'
        required: false
        type: 'string'
        default: 'false'
  schedule:
    - cron: '45 04 * * *'

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: prod
      BUILD_TYPE: dogfood
      UPLOAD_TO_PLAYSTORE: false
      FIRESTORE_ENABLED: false
      BUILD_BUSINESS: In Mea Ph Sea Hsi
      # If modifying `BUILD_BUSINESS`, update this value and also update the `workflow_dispatch` default value above.
    outputs:
      BRANCH: ${{ steps.set-outputs.outputs.BRANCH }}
      BUILD_BUSINESS: ${{ steps.set-outputs.outputs.BUILD_BUSINESS }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log Inputs
        run: |
          echo "Logging Inputs:"
          echo "Event Name: ${{ github.event_name }}"
          echo "BUILD_BUSINESS (input): ${{ github.event.inputs.BUILD_BUSINESS }}"
          echo "HOTFIX (input): ${{ github.event.inputs.HOTFIX }}"
          echo "BUILD_BUSINESS (env): ${{ env.BUILD_BUSINESS }}"
          echo "BUILD_BUSINESS (env2): $BUILD_BUSINESS"


      - name: Set environment name from UI
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.Create_Branch }}
        run: |
          echo "BUILD_BUSINESS=${{ github.event.inputs.BUILD_BUSINESS }}" >> $GITHUB_ENV

      - name: Set environment name from UI
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.Create_Branch }}
        run: |
          echo "BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "BUILD_BUSINESS=${{ github.event.inputs.BUILD_BUSINESS }}" >> $GITHUB_ENV

      - name: Set outputs
        id: set-outputs
        run: |
          echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT
          echo "BUILD_BUSINESS=$BUILD_BUSINESS" >> $GITHUB_OUTPUT

      - name: Print Working Directory
        run: pwd

      - name: List Files
        run: ls -R

      - name: Start Multibuild pipeline for release build
        run: cd ./scripts && ./run.sh

  test-inputs: 
    needs: [log-inputs]
    runs-on: ubuntu-latest
    steps: 
      - name: Set environment name
        run: |
          echo "BRANCH=${{ needs.log-inputs.outputs.BRANCH }}" >> $GITHUB_ENV
          echo "BUILD_BUSINESS=${{ needs.log-inputs.outputs.BUILD_BUSINESS }}" >> $GITHUB_ENV

  run-regression-test:
    #    if: ${{ always() && (contains(join(needs.*.result, ','), 'success') && (github.event_name == 'workflow_dispatch' && inputs.Create_Branch)) || github.event_name == 'schedule' }}
    if: ${{ always() && (contains(join(needs.*.result, ','), 'success') && ((github.event_name == 'workflow_dispatch')) || github.event_name == 'schedule' )}}
    needs: [ test-inputs ]
    uses: ayra98/workflow-testing/.github/workflows/regression-release-test.yml@master
    with:
      BRANCH_NAME: 'test'