name: Log Inputs Workflow

on:
  workflow_dispatch:
    inputs:
      BUILD_BUSINESS:
        description: 'Build Business one of In Mea Ph Sea Hsi'
        required: false
        type: 'string'
        default: 'In Mea Ph Sea Hsi'
      HOTFIX:
        description: 'Hotfix Build Generation?'
        required: false
        type: 'string'
        default: 'false'
  schedule:
    - cron: '00 04 * * 1' # Every Monday at 9:02 AM IST

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        run: |
          echo "Logging Inputs:"
          echo "Event Name: ${{ github.event_name }}"
          echo "BUILD_BUSINESS (input): ${{ github.event.inputs.BUILD_BUSINESS }}"
          echo "HOTFIX (input): ${{ github.event.inputs.HOTFIX }}"
          
          # Handle schedule event (inputs are not directly passed)
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "For schedule, using default values."
            echo "BUILD_BUSINESS (default): In Mea Ph Sea Hsi"
            echo "HOTFIX (default): false"
          fi